version: "3"

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./web:/usr/src/app/
    env_file: .env
    environment:
      DEBUG: "true"
    # docker_django has not been created yet so this obviously crashes on the service
    # so how do I create the project before this service runs through the
    # container itself?
    # tried using this command but nothing happens
    # docker-compose run web django-admin startproject django_project .
    # command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
    # command: python manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  web-django:
  web-static:
  pgdata:
